name: Github Pages Deploy

on:
  push:
    branches:
      - 'main'

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [15.x]

    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Check env variable
        run: echo "env exists ${{GITHUB_API_URL}}"

      - name: Install
        run: npm install
        env:
          REACT_APP_URL: ${{secrets.REACT_APP_URL}}

      - name: Build
        run: CI='' npm run build

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@4.1.5
        with:
          branch: gh-pages # The branch the action should deploy to.
          folder: build # The folder the action should deploy.

